name: Go

on:
  pull_request:
  push:

env:
  GO111MODULE: "on"

jobs:
  build:
    name: Build, Check and Test
    strategy:
      matrix:
        go-version: [1.12.x, 1.13.x, 1.14.x]
    runs-on: ubuntu-latest
    steps:
      - name: Install Go
        uses: actions/setup-go@v1
        with:
          go-version: ${{ matrix.go-version }}

      - name: Checkout code
        uses: actions/checkout@v2

      - name: Build
        run: go build ./...

      - name: golangci-lint
        uses: golangci/golangci-lint-action@v1
        with:
          version: v1.31

      - name: Test
        run: go test -v ./...